#! /usr/bin/env python

PROJECT = "Battery"
SITE = "dtomas"

import sys, os
sys.path.append(os.path.dirname(__file__))
sys.path.append(os.path.join(os.path.dirname(__file__), 'TrayLib'))
sys.path.append(
    os.path.join(os.path.dirname(__file__), 'rox-lib', 'ROX-Lib2', 'python')
)

import rox
try:
    from battery.main import BatteryMain
except ImportError:
    rox.croak("No suitable backend found.")
    sys.exit(1)

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

rox.setup_app_options(PROJECT, 'Options.xml', SITE)

BatteryMain().mainloop(sys.argv)
